name: Release
on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: anz-test-2

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build the Docker image
      run: make docker-build

    - name: Extract tag name
      id: tag
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Tag the Docker image
      env:
        GIT_VERSION: ${{ steps.tag.outputs.VERSION }}
      run: make tag

    - name: Login to Docker
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Publish to Docker
      env:
        GIT_VERSION: ${{ steps.tag.outputs.VERSION }}
      run: make publish
