name: Release
on:
	push:
		branches:
			- master
		tags:
			- v*

env:
	IMAGE_NAME: anz-test-2

jobs:
	publish:
		runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

		- name: Build the Docker image
			run: make docker-build

		- name: Tag the Docker image
			env:
				GIT_VERSION: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
			run: make tag

		- name: Login to Docker
			run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

		- name: Publish to Docker
			env:
				GIT_VERSION: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
			run: make publish

		- name: Create Release
			uses: actions/create-release@latest
			id: create_release
			with:
				tag_name: ${{ github.ref }}
				release_name: Release ${{ github.ref }}
				body: |
					Releasing version ${{ github.ref }} of the ANZx Technical Test 2
				draft: false
				prerelease: false
