name: Test
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Setup system libraries
      run: sudo apt update && sudo apt install -y git build-essential

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get cached modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: make test
